# Generated by Django 3.2.9 on 2021-11-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
